name: Code Review with GPT
on: [pull_request]

jobs:
  code_review:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run code review
      run: |
        python review_code.py
    ```

